### ISSUE TITLE
Find a bug in file 'model/Seq2seqModel.py'

### ISSUE THREAD

**Issue by zephyrxvxx7** [Wooyong-Choi/seq2seq_pytorch#1]
Hi,
I find a bug in this file line 44, There lack a parameter 'bidirection'.
If I set 'gpu_id' not equal as 1, Pytorch will return a RuntimeError: Expected hidden size ...

So I suggest you modify this file to avoid this bug.

I am watching this repositories, keep it up.
Have a good day.

**Comment by Wooyong-Choi** [comment]
Hi zephyrxvxx7,
Thank you for your reporting!

I will modify the source as soon as possible.
I think there's some missed commit to the repo.
